kind: Secret
apiVersion: v1
metadata:
  name: statistics-service-secret
data:
  MONGODB_URI: bW9uZ29kYjovL3VzZXI6cGFzc3dvcmRAbW9uZ29kYjoyNzAxNy9zdGF0aXN0aWNzZGI=
  STATISTICS_SERVICE_PASSWORD: c3RhdGlzdGljcy1hdXRoLXNlY3JldA==
type: Opaque
